# Generated by Django 2.2.2 on 2019-06-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.FileField(blank=True, default='img/avatar.png', upload_to='img/'),
        ),
    ]
