# Generated by Django 2.2.2 on 2019-06-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190621_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.FileField(blank=True, default='img/avatar.png', upload_to='img/')),
            ],
        ),
    ]
