# Generated by Django 2.2.2 on 2019-06-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_galleryview'),
    ]

    operations = [
        migrations.CreateModel(
            name='videogallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('videofile', models.FileField(upload_to='video/', verbose_name='video File')),
            ],
        ),
    ]
