# Generated by Django 2.2.2 on 2019-06-26 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_videogallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='videogallery',
        ),
    ]
