# Generated by Django 2.2.2 on 2019-06-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_videogallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('audiofile', models.FileField(upload_to='audio/')),
            ],
        ),
    ]
